name: Comment on PR Commit

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const author = context.payload.pull_request.user.login;
            const body = `Hi, thanks for the commit @${author} 🎉`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: body
            });
