name: Comment on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const author = context.payload.pull_request.user.login;

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: `Hi, thanks for the commit @${author}! 🚀`
            });
